version: "3" #This denotes that we are using version 3 of Docker Compose
services: #This section defines all the different containers we will create.
  avantio-back-node: #This is the name of our Nextjs application.
    image: node:alpine
    working_dir: "/src"
    volumes:
      - .:/src
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - mongodb
    env_file:
      - .env
  avantio-back-test-e2e:
    image: node:alpine
    working_dir: "/src"
    volumes:
      - .:/src
    command: npm run dev
    depends_on:
      - mongodb
    env_file:
      - .env.e2e
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=database
    logging:
      driver: none
